### ISSUE TITLE
Script uploaded to JSS not populating

### ISSUE THREAD

**Issue by golbiga** [sheagcraig/JSSImporter#19]
When adding a script to a jss.recipe the contents of the script are not showing up in the JSS. The script itself is there, but the script contents are empty. In the RECIPE_DIR is the script and app specific scripttemplate.xml. The actual jss.recipe has the appropriate fields added for scripts.

When I try to download the script from within the JSS GUI it's downloading the file with filename.sh.txt and the contents of that file are empty. Not sure if I'm doing something wrong here.

Thanks
Allen

**Comment by sheagcraig** [comment]
@golbiga I have this "working". It has thrown my object hierarchy into a tizzy, so I'm contemplating how to refactor and restructure to make it "make sense". But it does indeed work.

**Comment by golbiga** [comment]
@sheagcraig I'm still having issues post upgrade. It's still trying to copy the script to a distribution point and not to the database. I added JSS_MIGRATED true to com.github.autopkg.plist

If /data/caspershare/Scripts exists the script is copied there but is blank in the JSS and shows up as missing. If /data/caspershare/Scripts is removed i get the following:

JSSImporter: Script: TextMate2Preinstall.sh created.
JSSImporter: Copying /Users/admin/Library/AutoPkg/RecipeRepos/com.github.golbiga.recipes/JSS/TextMate2Preinstall.sh to all distribution points.
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 672, in main
    self.scripts = self.handle_scripts()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 511, in handle_scripts
    self._copy(script['name'], id_=script_object.id)
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 381, in _copy
    self.j.distribution_points.copy(source_item, id_=id_)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.4-py2.7.egg/jss/distribution_points.py", line 204, in copy
    repo.copy_script(filename, id_)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.4-py2.7.egg/jss/distribution_points.py", line 385, in copy_script
    'Scripts', basename))
  File "/Library/Python/2.7/site-packages/python_jss-0.5.4-py2.7.egg/jss/distribution_points.py", line 414, in _copy
    shutil.copyfile(full_filename, destination)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: u'/Volumes/CasperShare/Scripts/TextMate2Preinstall.sh'

I tried the JDS trick but it simply adds a blank TextMate2Preinstall.sh file as well.

Thanks
Allen

**Comment by sheagcraig** [comment]
Hey @golbiga!

Based on the traceback, I think I see what is happening. The very last bit mentions the copy is using shutil.copyfile, which should not be the case here. It should be using ```distribution_points.SMBDistributionPoint._copy_script_migrated()```

AFP and SMB repos can be configured with just the share's "name" and password. The rest of the information to connect is pulled from the Distribution Points API call. As it stands, the ```AFPDistributionPoint``` and ```SMBDistributionPoint``` have no reference to a ```jss.JSS``` object, so they don't *know* whether ```JSS_MIGRATED``` has been set or not.

And the conditions I check for are whether a ```jss.JSS``` object has been passed to the AFP/SMB repo constructor AND that it has ```JSS_MIGRATED=True```.

So I'm guessing you didn't divine the magical incantation! This is primarily a documentation issue, but also a python-jss vs. JSSImporter issue. I'm going to add in some code to pass the correct data around for the auto-detection scheme mentioned above so you don't have to add anything extra into your config. Only people who are explicitly configuring AFP and SMB shares outside of the DistributionPoints class will ever need to worry about this, and it is documented in the docstring.

Just to see it "work" and confirm that this methodology works, you can give this a try:

```
# curl -u <username> 'https://<URL>:<PORT>/dbfileupload' -H 'DESTINATION: 1' -H 'OBJECT_ID: -1' -H 'FILE_TYPE: 3' -H 'FILE_NAME: <FILENAME>' -d '@<FULL_PATH_TO_FILE>' -X POST
```

e.g.:
```
# curl -u admin 'https://turtlepower.org:8443/dbfileupload' -H 'DESTINATION: 1' -H 'OBJECT_ID: -1' -H 'FILE_TYPE: 3' -H 'FILE_NAME: find_printer.py' -d '@/Users/scraig/Desktop/find_printer.py' -X POST
```

If you get it wrong, curl and the JSS will often give you a response of "Success", even though nothing happened. You'll know it worked because
- The script will show up on your JSS
- The JSS will respond with an md5 checksum and a received size
	- e.g. ```<?xml version="1.0" encoding="UTF-8" standalone="yes"?><uploadResponse><id>38</id><md5>571073a50c394367b05737ff4056e89a</md5><message></message><receivedSize>683</receivedSize><successful>true</successful></uploadResponse>```

Can I slip you a testing version once I get it updated? That way I can release again with the comfort of knowing that it works correctly!

**Comment by sheagcraig** [comment]
Yeah-try grabbing ```jss/distribution_points.py``` from the testing branch and copying it in over your installed one. Works for me (and I was able to recreate your issue).

**Comment by golbiga** [comment]
Just swapped out distribution_points.py and the scripts are now being uploaded properly. Thanks!

**Comment by sheagcraig** [comment]
Phew! I'm glad that works.

I've got a PR to review; after that I'll push a release. Thanks for bringing to my attention.

**Comment by grahampugh** [comment]
I've also got this problem. I've set JSS_MIGRATED to True but it is still "copying" the script to the distribution point:

```
JSSImporter: Script: Carbon Copy Cloner-postinstall.sh created.
JSSImporter: Copying /Users/Shared/Jenkins/Library/AutoPkg/RecipeOverrides/Carbon Copy Cloner-postinstall.sh to all distribution points.
JSSImporter: Copying to id-jds-prd.ethz.ch
JSSImporter: Copied /Users/Shared/Jenkins/Library/AutoPkg/RecipeOverrides/Carbon Copy Cloner-postinstall.sh
```

It cannot really be copying it, because I do not have a Scripts folder - this is a new setup built originally as 9.100, so there's never been a scripts folder. But still, Casper Admin shows the script as "missing" and there is an empty script object in the database.  I'm using the default way of setting up the JSSImporter settings. Is there some other value that has to be set?

```
$ defaults read com.github.autopkg
{
    "API_PASSWORD" = blahblah;
    "API_USERNAME" = AutoPkg;
    "JSS_MIGRATED" = True;
    "JSS_REPOS" =     (
                {
            name = JPShare;
            password = "blahblahblah";
        }
    );
    "JSS_URL" = "https://jamfproserver/template";
}

**Comment by sheagcraig** [comment]
@grahampugh are you using or testing the JSSImporter testing release? It should solve this issue (it does away with the `JSSI_MIGRATED` value entirely.

**Comment by grahampugh** [comment]
Hi Shea

Yes we started using that and it works well.  Is that release now the one that your AutoPkg recipe points to?

PS your JSSImporter came up a LOT in JNUC this year.  I’m very interested in helping extend its functionality to the new Patch Policies, which will be separately populated. I guess it needs a new Processor.

Cheers
Graham
