### ISSUE TITLE
JSSImporter doesn't seem to update python-jss

### ISSUE THREAD

**Issue by homebysix** [sheagcraig/JSSImporter#25]
After manually installing the latest release .pkg of JSSImporter (0.3.6), I get the following error when running AdobeFlashPlayer.jss:
```
Processing AdobeFlashPlayer.jss...
AdobeFlashURLProvider
AdobeFlashURLProvider: Found URL http://fpdownload.macromedia.com/get/flashplayer/pdc/16.0.0.305/install_flash_player_osx.dmg
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/it/Library/AutoPkg/Cache/local.jss.AdobeFlashPlayer/downloads/AdobeFlashPlayer.dmg
EndOfCheckPhase
Versioner
Versioner: Mounted disk image /Users/it/Library/AutoPkg/Cache/local.jss.AdobeFlashPlayer/downloads/AdobeFlashPlayer.dmg
Versioner: Found version 16.0.0.305 in file /private/tmp/dmg.AuOI8j/Install Adobe Flash Player.app/Contents/Info.plist
PkgCopier
PkgCopier: Mounted disk image /Users/it/Library/AutoPkg/Cache/local.jss.AdobeFlashPlayer/downloads/AdobeFlashPlayer.dmg
PkgCopier: Copied /private/tmp/dmg.gvAg1R/Install Adobe Flash Player.app/Contents/Resources/Adobe Flash Player.pkg to /Users/it/Library/AutoPkg/Cache/local.jss.AdobeFlashPlayer/AdobeFlashPlayer-16.0.0.305.pkg
JSSImporter
JSSImporter: Requires python-jss version: 0.5.4. Installed: 0.5.3
```
The last line makes me think that the installer didn't work. I verified that the file at `/Library/Python/2.7/site-packages/jss/__init__.py` does indeed end with `__version__ = "0.5.3"`.

**Comment by sheagcraig** [comment]
A little easier to write long paths and stuff out here than on the Twitter!

So the way it is *supposed* to work *now* is that the disutils commandline app "easy_install" is used to postinstall-script install the python egg file for python-jss using the python packaging system. Then it runs again with the update flag on to grab a newer one from pypi.org if it exists (this was to avoid people with bad/poor network connectivity to install without errors.

The old installer just copied the python-jss files into ```/Library/Python/2.7/site-packages/jss
which is why I suspect that your site-packages folder *only* has the jss folder from an older installer putting it there (or a manual install from source?)

My dev machine is a cluster and I need to start using virtualenvs... But I think you should be totally safe to just remove the .../site-packages/jss folder and reinstall from the JSSImporter package, which should run the easy_install again. Then you should see not a jss folder in there, but instead a folder that looks like ```python_jss-0.5.5-py2.7.egg``` (which the packaging system recognizes as "jss" when you do an import).

Let me know, of course, because if the package installer is busted I want to fix it!

**Comment by homebysix** [comment]
I think we've determined that since this box has a custom version of Python installed at /usr/local/bin/python, python-jss is getting installed into /usr/local/lib/python2.7/site-packages. But then AutoPkgr is looking for python-jss in /Library/Python/2.7/site-packages and not finding it.

The custom version of Python is necessary on this particular Mac for other things, so what's the best workaround? I tried copying the python-jss egg folder manually into /Library/Python/2.7/site-packages, but no joy.

**Comment by homebysix** [comment]
Manually running `easy_install python-jss` produces:
```
Searching for python-jss
Best match: python-jss 0.5.5
Processing python_jss-0.5.5-py2.7.egg
Adding python-jss 0.5.5 to easy-install.pth file

Using /Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg
Processing dependencies for python-jss
Finished processing dependencies for python-jss
```

**Comment by justinrummel** [comment]
I just noticed this thread while troubleshooting my [Oracle Java 7 override](https://github.com/homebysix/auto-update-magic/issues/10), and verified that I have the latest JSSImporter 0.3.6, however only 0.5.4 of python-jss.

```
sadmin@mo ~> ll /Library/Python/2.7/site-packages/ | grep jss
drwxr-xr-x  4 root  wheel   136B Dec  2 11:27 python_jss-0.4.2-py2.7.egg
-rw-r--r--  1 root  staff   451K Dec  2 13:52 python_jss-0.4.3-py2.7.egg
drwxr-xr-x  4 root  wheel   136B Dec  4 16:07 python_jss-0.5.1-py2.7.egg
drwxr-xr-x  4 root  wheel   136B Dec 17 13:31 python_jss-0.5.3-py2.7.egg
drwxr-xr-x  4 root  wheel   136B Feb  3 11:20 python_jss-0.5.4-py2.7.egg
sadmin@mo ~> grep __version__ /Library/AutoPkg/autopkglib/JSSImporter.py
    from jss import __version__ as PYTHON_JSS_VERSION
__version__ = '0.3.6'
```

**Comment by sheagcraig** [comment]
@justinrummel This is the first release where new features in python-jss were not required in JSSImporter. So the last release package i built (with included python-jss 0.5.4) is not going to be "current" with python-jss. The only way it would get to 0.5.5 is if you either reinstalled the package (because it has a postinstall script to run an ```easy_install``` update or manually updated python-jss.

In theory, when the next update comes out for JSSImporter, it should update to whatever is the newest available at pypi.org/python-jss. If you want to make it update now, you can always do
```easy_install -U python-jss``` or if you have pip installed, ```pip install -U python-jss```.

I'm looking at homebysix/auto-update-magic/#10 right now. It's definitely an issue with Ext. attributes. I'll file an issue over here or on python-jss if it seems appropriate.

**Comment by sheagcraig** [comment]
@homebysix Okay, I hope things are straightened out now! Package management on python is kind of a cluster. 
- I think if you just copy the jss folder into the appropriate site-packages, everything *works*, but it's not managed by the package management (so you can't just upgrade with pip or easy_install). 
- If you just copy the python-jss egg directory in, it won't work because the package manager doesn't know about it. (I think, and I don't have time to test it at the moment, but it sounds like you tried it, as per above, and it didn't work).

JSSImporter and AutoPkg use ```#!/usr/bin/python``` in the shebang line because that's where Apple puts python. This is to ensure maximum compatibility with OS X systems. If a custom-installed python overwrites, replaces with a link to a different python, or if your path has a custom python with higher precedence than the system one, stuff gets jacked up.

I see this a lot with our student programming labs. They use pygame a lot, which requires Foundation. Only the Apple python "comes" with Foundation, so whenever they go out to download Python from Python.org, they can never get pygame to work.

For your situation, hopefully the above information allows you to make an informed opinion and plan for upgrades. I would think the easiest solution is just to manually upgrade python-jss whenever you install the JSSImporter packages, since you probably can't work around the custom python requirement.

**Comment by homebysix** [comment]
Sounds good. Thanks for the info!
