### ISSUE TITLE
Error when using override to "remove" keys...

### ISSUE THREAD

**Issue by everetteallen** [sheagcraig/JSSImporter#33]
So seeing the error below with an Override (also below) of a .jss recipe that just tries to "remove" keys (i.e. set them to no value).  The interesting thing is that the override recipe actually works correctly putting everything on the JSS but throws the error.  Maybe I am doing something wrong?
---
2/26/15 3:18:59.453 PM AutoPkgr[32190]: (FULL AUTOPKG TRACEBACK) 
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 671, in main
    self.groups = self.handle_groups()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 393, in handle_groups
    computer_group = self._add_or_update_smart_group(group)
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 428, in _add_or_update_smart_group
    update_env="jss_group_updated", added_env="jss_group_added")
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 449, in _update_or_create_new
    with open(os.path.expanduser(template_path), 'r') as f:
IOError: [Errno 2] No such file or directory: u''
---
With this override:
---
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Identifier</key>
	<string>local.jss.UNCWide-AutoPKG-GoogleChrome</string>
	<key>Input</key>
	<dict>
		<key>CATEGORY</key>
		<string>aaUNC-System-Test</string>
		<key>DESCRIPTION</key>
		<string>Google Chrome is a browser that combines a minimal design with sophisticated technology to make the web faster, safer, and easier.</string>
		<key>GROUP_NAME</key>
		<string></string>
		<key>GROUP_TEMPLATE</key>
		<string></string>
		<key>ICON</key>
		<string></string>
		<key>JSS_INVENTORY_NAME</key>
		<string>Google Chrome.app</string>
		<key>NAME</key>
		<string>UNCWide-AutoPKG-GoogleChrome</string>
		<key>POLICY_CATEGORY</key>
		<string></string>
		<key>POLICY_TEMPLATE</key>
		<string></string>
	</dict>
	<key>ParentRecipe</key>
	<string>com.github.autopkg.jss.googlechrome</string>
</dict>
</plist>
```
---

**Comment by everetteallen** [comment]
So spoke too soon the package is not actually uploaded to the JSS but the record is created.
Ugh.

**Comment by sheagcraig** [comment]
Hey Everette,
I think I have a solution.

The failure is at the group handling stage, at least as posted above. The way JSSImporter currently detects whether a group is configured to be added or not is by whether the groups key is populated with data. It doesn't validate that data, however.

So in your override, you have overriden the ```GROUP_NAME``` and ```GROUP_TEMPLATE``` input variables to be blank. Further down in the parent recipe, however, the *actual* group section is still intact, and it is replacing the single group entry's ```name``` and ```template_path``` values with the blank values specified above. This is not the same thing as having *no* groups value.

Specifically, to accomplish what you seem to be trying to do with the override above, your recipe should look like this:
```
<?xml version="1.0" encoding="UTF-8"?>                                             
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">                                                              
    <dict>                                                                         
        <key>Description</key>                                                     
        <string>Uses parent pkg recipe to download latest GoogleChrome and import it into the JSS.</string>
        <key>Identifier</key>                                                      
        <string>com.github.autopkg.jss.googlechrome</string>                       
        <key>Input</key>                                                           
        <dict>                                                                     
            <key>NAME</key>                                                        
            <string>GoogleChrome</string>                                          
            <key>JSS_INVENTORY_NAME</key>                                          
            <string>Google Chrome.app</string>                                     
            <key>CATEGORY</key>                                                    
            <string>Productivity</string>                                          
            <key>POLICY_CATEGORY</key>                                             
            <string>Testing</string>                                               
            <key>POLICY_TEMPLATE</key>                                             
            <string>%RECIPE_DIR%/PolicyTemplate.xml</string>                       
            <key>ICON</key>                                                        
            <string>%RECIPE_DIR%/GoogleChrome.png</string>                         
            <key>GROUP_NAME</key>                                                  
            <string>%NAME%-update-smart</string>                                   
            <key>GROUP_TEMPLATE</key>                                              
            <string>%RECIPE_DIR%/SmartGroupTemplate.xml</string>                   
            <key>DESCRIPTION</key>                                                 
            <string>Google Chrome is a browser that combines a minimal design with sophisticated technology to make the web faster, safer, and easier.</string>
        </dict>                                                                    
        <key>MinimumVersion</key>                                                  
        <string>0.4.0</string>                                                     
        <key>ParentRecipe</key>                                                    
        <string>com.github.autopkg.pkg.googlechrome</string>                       
        <key>Process</key>                                                         
        <array>                                                                    
            <dict>                                                                 
                <key>Arguments</key>                                               
                <dict>                                                             
                    <key>prod_name</key>                                           
                    <string>%NAME%</string>                                        
                    <key>jss_inventory_name</key>                                  
                    <string>%JSS_INVENTORY_NAME%</string>                          
                    <key>category</key>                                            
                    <string>%CATEGORY%</string>                                    
                    <key>policy_category</key>                                     
                    <string>%POLICY_CATEGORY%</string>                             
                    <key>policy_template</key>                                     
                    <string>%POLICY_TEMPLATE%</string>                             
                    <key>self_service_icon</key>                                   
                    <string>%ICON%</string>                                        
                    <key>self_service_description</key>                            
                    <string>%DESCRIPTION%</string>                                 
                    <key>groups</key>                                              
                    <array/>                                                        
                    </dict>                                                            
                <key>Processor</key>                                               
                <string>JSSImporter</string>                                       
            </dict>                                                                
        </array>                                                                   
    </dict>                                                                        
</plist>
```

The blank policy and icon sections should work correctly, but since the recipe is set up to use the input variables to fill in the single group entry, an override won't work, and you'll have to (at least at this time), edit the groups section manually to be empty.

Some further ideas:
- You could scope it to a dummy static group with no members to just "make it work".
- I can see how this defeats the purpose of having an input variable at the top. As we've discussed before, this is an oversight on my part because it never occurred to me that someone would want to *not* scope to a group! So the input variable allows one to override the group that it *does* get scoped to, but not to skip scoping entirely. I may be able to add some kind of recipe validation to the processor so that it looks for more than just a groups = None, but instead looks for a groups with an array with no *useful* values as well. This would potentially be an issue with recipes that use scripts and extension attributes too, since they can have an arbitrary number of scripts/ea added in each recipe.

Let me add it to the todo list. I would think that for testing purposes and making progress purposes, either scoping to a dummy group or making edits to the recipes you use would be the way to go.

I'm pretty sure you could bulk edit them with defaults delete in a for loop in a bash script!
