### ISSUE TITLE
Enhancement: Set boot_volume_required

### ISSUE THREAD

**Issue by novaksam** [sheagcraig/JSSImporter#38]
I was looking at if this could be done simply, but it looks like it might take a little more knowledge than I currently have.

I looked at python-jss and something will have to be added there to set boot_volume_required, but most of the work will (probably) need to be done in JSSImporter.

**Comment by sheagcraig** [comment]
What is boot_volume_required an option for?

**Comment by novaksam** [comment]
It's the parameter that tells packages to install on reboot. It's for those packages that have scripts that need/should run when the machine is running.

**Comment by sheagcraig** [comment]
Ah, got it. That's what I thought it was, but wanted to double-check.

Confirmed that ```boot_volume_required``` is a property of packages.

This is getting back to that idea of where (and how many places) these settings should be housed. Should it be an argument for JSSImporter, or something to put in the template for one recipe?

But in this case, there is no *package* template, so I think the appropriate place would be an input variable/argument to JSSImporter.

I follow the logic on there being packages that, due to scripts and whatnot, need to be installed when the machine is booted from its drive, not from a netboot image or something.

Really, what we're talking about here, then, is making sure packages are configured this way for inclusion in Casper Imaging workflows, right?

The thing I always start to fall back on is that AutoPkg and JSSImporter are supposed to be part of a testing pipeline. I don't really see it as part of an imaging workflow, and I know the community best-practice really is to image just the OS and then install packages after imaging.

However, it's really nice to have the recipes be documentation for and an implementation of those packages ultimate use. If someone on the admin team had to (remember to) manually toggle the boot_volume_required every time an updated package was promoted to production, there would be mistakes.

For those organizations which *do* install packages as part of an imaging workflow, this would be really helpful.

I honestly think it sounds like rather than create an option, it almost makes more sense to just add the setting set to True to ALL packages, because then you don't have to worry about it if you use them for imaging or never use them during imaging. And that way it's not another option filling up space in the documentation or in the recipes, or another thing to forget to edit into a new recipe.

Since AutoPkg only produces *packages*, this seems to make sense. If it made dmg's too, that would be another story, but I think it makes sense.

Do you feel like these are the main points of the need for this?

**Comment by novaksam** [comment]
Yeah I think that covers it. Since it really only affect installation via imaging the usage is isolated to admins who shift autopkg pkgs over into production for imaging.

**Comment by novaksam** [comment]
This was working for me until I updated JSSImporter (and python-jss). It's possible that I modified one of the python files to accommodate this, but I thought I'd ask you.

**Comment by sheagcraig** [comment]
I think that's probably the case. Let me get that PR pulled in and then we can close these out.

**Comment by sheagcraig** [comment]
JSSImporter uses python-jss' `Package` initializer to run the `new` method. With the 1.1.0 update I just pushed, JSSImporter should be ready to rock.

Let me know if it's not! You'll have to update python-jss manually, probably:
`easy_install -U python-jss`

**Comment by novaksam** [comment]
Looks good to me! Thanks!

From: Shea Craig
Reply-To: sheagcraig/JSSImporter
Date: Thursday, July 2, 2015 at 8:25 AM
To: sheagcraig/JSSImporter
Cc: Information Technology
Subject: Re: [JSSImporter] Enhancement: Set boot_volume_required (#38)


JSSImporter uses python-jss' Package initializer to run the new method. With the 1.1.0 update I just pushed, JSSImporter should be ready to rock.

Let me know if it's not! You'll have to update python-jss manually, probably:
easy_install -U python-jss
