### ISSUE TITLE
JSSImporter fails with umlauts in self_service_description

### ISSUE THREAD

**Issue by systemheld** [sheagcraig/JSSImporter#61]
Hello Shea,

We have some problems when using umlauts in the Self Service Description. At the moment we work around with converting to their alternative notation (such as ö -> oe), but thats a bit ugly. I did some research but can't find the place where the ascii conversion is done. In your JSSImporter you are encoding all strings to utf-8 - as long as I can see that - so the problem must resist in some library.

If I run a debug run, there isn't much helpful output to locate the ascii conversion:
```
'self_service_description': Der kostenlose Instant-Messenger verbindet sich mit allen g\xe4ngigen Chatprotokollen \u2013 von MSN Messenger \xfcber Yahoo Messenger bis hin zu AOL, ICQ und Twitter.'
[...]
JSSImporter: Found file: /Users/me/Library/AutoPkg/RecipeRepos/de.fau.rrze.gitlab.faumac.autopkg/Adium/../InstallPolicyTemplate.xml
'ascii' codec can't encode character u'\xe4' in position 729: ordinal not in range(128)
```

Any Ideas?

**Comment by sheagcraig** [comment]
It looks like the description string below has a combination of unicode (\u2013) and encoded ascii (\xe4). This is probably due to my poor handling of Unicode!

From: Oliver
Reply-To: sheagcraig/JSSImporter
Date: Friday, September 18, 2015 at 10:47 AM
To: sheagcraig/JSSImporter
Subject: [JSSImporter] JSSImporter fails with umlauts in self_service_description (#61)


Hello Shea,

We have some problems when using umlauts in the Self Service Description. At the moment we work around with converting to their alternative notation (such as ö -> oe), but thats a bit ugly. I did some research but can't find the place where the ascii conversion is done. In your JSSImporter you are encoding all strings to utf-8 - as long as I can see that - so the problem must resist in some library.

If I run a debug run, there isn't much helpful output to locate the ascii conversion:

'self_service_description': Der kostenlose Instant-Messenger verbindet sich mit allen g\xe4ngigen Chatprotokollen \u2013 von MSN Messenger \xfcber Yahoo Messenger bis hin zu AOL, ICQ und Twitter.'
[...]
JSSImporter: Found file: /Users/me/Library/AutoPkg/RecipeRepos/de.fau.rrze.gitlab.faumac.autopkg/Adium/../InstallPolicyTemplate.xml
'ascii' codec can't encode character u'\xe4' in position 729: ordinal not in range(128)


Any Ideas?

—
Reply to this email directly or view it on GitHub<https://github.com/sheagcraig/JSSImporter/issues/61>.



This communication (including any attachments) is intended for the use of the intended recipient(s) only and may contain information that is confidential, privileged or legally protected. Any unauthorized use or dissemination of this communication is strictly prohibited. If you have received this communication in error, please immediately notify the sender by return e-mail message and delete all copies of the original communication. Any views or opinions presented are solely those of the author.

**Comment by sheagcraig** [comment]
On 11/8/12, 12:07 PM, "Kagi (sm)" <admin@kagi.com> wrote:

>Payment fee received:
>1 Quantity Payment for Pacifist, US 20.00
>
>Registered-To: Shea Craig
>Email: shea.craig@da.org
>Postal: 3601 Ridge Rd., Durham NC 27705, United States
>Total Amount Paid: USD 20.00
>Date: 2012-11-08
>Processed: 2012-11-08
>PaymentMethod: card
>Invoice: I723402079
>TransactionID: CHNPV76A0PHG
>Route: S1A5T0R1
>Note: SSL from 64.132.104.70 via KOOP 6.8.4en for supplier N4M.
>
>Thank you for registering Pacifist!
>
>Your username and registration code are below. Please save this e-mail to a file or print it for future reference.
>
>User: Shea Craig
>Registration code: 1COAGn7T0K-3Lr7fZXOa2-02E
>
>To enter this code, simply launch Pacifist and click "Enter Code..." when the registration window appears. Enter the user name and registration code exactly as they appear above. Both the user name and registration code are case-sensitive, so it is recommended that you enter the code by copying and pasting it from this e-mail into the code entry screen. Be sure to copy only the code and not any leading or trailing spaces or line breaks when doing so.
>
>Pacifist is currently at version 3.0.10. If you are running an older version, you can point your web browser at http://www.charlessoft.com to download the latest version.
>
>If you have any questions or comments, please feel free to contact me at csrstka@kagi.com or support@charlessoft.com.
>
>Thanks for supporting shareware!
>
>Charles Srstka
>SQNM-csrstkaPCFT 1893
>
>
>**********************************************************
>** PLEASE READ THIS ENTIRE E-MAIL MESSAGE FOR IMPORTANT INFORMATION ABOUT YOUR PURCHASE. **
>
>Thank you for purchasing from the Kagi store. For future reference regarding this order, please use the following url:     https://secure.kagi.com/cgi-bin/WebObjects/PQ.woa/wa
>
>If you don't find what you want there, please use the online form at that web page to ask your questions. You can also visit : http://shop.kagi.com/
>
>Please remember technical support for the product you purchased is provided by the product manufacturer.
>
>Kagi
>1442-A Walnut Street #392
>Berkeley CA 94709-1405  USA
>SQNM-kagi 4566
>
>
>
>
>SC-TFYP 5.1 25


This communication (including any attachments) is intended for the use of the intended recipient(s) only and may contain information that is confidential, privileged or legally protected. Any unauthorized use or dissemination of this communication is strictly prohibited. If you have received this communication in error, please immediately notify the sender by return e-mail message and delete all copies of the original communication. Any views or opinions presented are solely those of the author.

**Comment by ocoda** [comment]
Well, I think that should not be public ;-)

**Comment by sheagcraig** [comment]
Pending python-jss update.
