### ISSUE TITLE
Applications in Non-Default Locations

### ISSUE THREAD

**Issue by beckf** [sheagcraig/JSSImporter#66]
I noticed that if there is an application that is not in the default install location (i.e. user copies application to Desktop, ~/Applications, or ~/Downloads), policies are running over and over again because the computer never falls out of the smart group in JAMF.  So the application in the default location is updated repeatedly because the other application is found and tracked by JAMF.  JAMF shows multiple instances of the application with different versions and different paths.  It doesn't look like you can specify application path to the smart group either.

**Comment by sheagcraig** [comment]
Hey @beckf! No! The `Application Title` criteria appears to pull from the "inventory", which is set with the JSS settings for inventory collection. By default, I think it only looks in `/Applications` and its subdirectories (although with El Cap we can no longer modify Utilities, so that's kind of uninteresting now). I think there's a checkbox for also including `/Library/Internet Plugins`, but beyond that, I'm not sure whether `~/Applications` is also included.

Ideally, JSSImporter is only making self-service policies under these circumstances. If there was any API access to policy logs, one could create some kind of process to look for repeatedly running "ongoing" policies that do package installs successfully... And do a more thorough check across the drive for multiple copies.

You can get at the policy logs with sql... But that's got some real hazards, as we've discussed!

So honestly, I think the best solution(s) are to a.) Only use ongoing-frequency policies as self-service initiated installs, and b.) Possibly try to tune the inventory collection to exclude `~/Applications|Desktop|Downloads`.

Any thoughts?

**Comment by beckf** [comment]
Hey Shea,

You are right about the location.  I double checked our settings, and it only looks at /Applications.  The problem we saw was with multiple instances of Microsoft Office installed in Applications.  I will investigate more.  Thanks!
