### ISSUE TITLE
Add option to cache instead of install in policy

### ISSUE THREAD

**Issue by charliwest** [sheagcraig/JSSImporter#75]
Mentioned in slack, but thought I would open this ticket in case anyone can figure out a fix for it.

I would like to be able to scope a policy that caches packages instead of installs them straight away. This would be useful for users who for whatever reason dont get updates installed very often, you can then have the cached package install another time, possibly while off the network, or late at night etc.

Bonus points if you can also have it delete older versions if they are already cached ;)

**Comment by sheagcraig** [comment]
So is it safe to assume that since the issue is posted on JSSImporter, you mean specifically that you want to be able to have AutoPkg'd updates set up as policies which cache rather than install?

At the moment, this goes all the way back to the Policy object in python-jss: https://github.com/sheagcraig/python-jss/blob/master/jss/jssobjects.py#L801

This method could have a changed signature which adds a parameter for action type which defaults to install, but could be instead set to cache. I'll add a feature request to python_jss for that.

Then, once python_jss supports it, as it stands at the moment, JSSImporter would need to add an input variable for it, since the current template system would not be able to handle it. I'm sure that a more full-featured templating system _could_ handle it.

If anybody wants to take this on with some oversight, that would make it happen a lot faster.

As for the bonus points, I'm not aware at all of how the caching works, but I'm pretty confident that there's nothing we can do through the API to manage that.

**Comment by charliwest** [comment]
> So is it safe to assume that since the issue is posted on JSSImporter, you mean specifically that you want to be able to have AutoPkg'd updates set up as policies which cache rather than install?
Yes thats correct.
> If anybody wants to take this on with some oversight, that would make it happen a lot faster.
I would like to help, but will mean learning python first, I did have a poke around and all I managed was to break it :) but will keep on if I find some time and update if it goes anywhere.
> As for the bonus points, I'm not aware at all of how the caching works, but I'm pretty confident that there's nothing we can do through the API to manage that.
I now realise this could probably be accomplished with a script in the recipe with a rm of the cached packages dir minus the version number and adding a star. Will figure that out soon.

**Comment by da-systems** [comment]
This is what I am looking for too. Being able to set <package_configuration> to
 <action>Cache</action> preferably in the PolicyTemplate-custom.xml would be awesome.

This would fit in with a patchoo workflow.

**Comment by sheagcraig** [comment]
This has been added to the 1.0.0 release (see the current testing branch to test).
