### ISSUE TITLE
Header value 0 must be of type str or bytes

### ISSUE THREAD

**Issue by homebysix** [sheagcraig/JSSImporter#88]
Yo! Got an interesting error at a client who is using an Amazon CDP as their master. The first time a JSS recipe is run, a package object is created but the package upload fails. Here's the verbose output of `autopkg run -v com.github.jss-recipes.jss.Firefox_EN`:

```
JSSImporter
JSSImporter: Category type: category-'Productivity' already exists according to JSS, moving on...
JSSImporter: Category type: policy_category-'Testing' already exists according to JSS, moving on...
JSSImporter: Copying /Users/foo/Library/AutoPkg/Cache/com.github.jss-recipes.jss.Firefox_EN/Firefox-48.0.2.pkg to all distribution points.
JSSImporter: Copying to https://jss.example.com:8443
Header value 0 must be of type str or bytes, not <type 'int'>
Failed.
Receipt written to /Users/foo/Library/AutoPkg/Cache/com.github.jss-recipes.jss.Firefox_EN/receipts/Firefox-receipt-20160913-100420.plist

The following recipes failed:
    Firefox.jss
        Error in com.github.jss-recipes.jss.Firefox_EN: Processor: JSSImporter: Error: Header value 0 must be of type str or bytes, not <type 'int'>

Nothing downloaded, packaged or imported.
```

Subsequent JSS recipe runs succeed, but with "Package upload not needed." And the package shows up as red (missing) in Casper Admin, proving that the file doesn't exist.

Looks like somebody on JAMF Nation is [seeing the same error](https://jamfnation.jamfsoftware.com/discussion.html?id=21205#respond) when uploading to a JDS.

And there's a suspiciously similar issue reported [here](https://github.com/Numergy/openvsd/issues/26) that seems related to a specific version of `requests`.

**Comment by homebysix** [comment]
**Update**: This was fixed by updating to the latest version of python-jss, released yesterday. [This PR was the fix](https://github.com/sheagcraig/python-jss/pull/55/files).

Thanks!

**Comment by sheagcraig** [comment]
All the credit on that one goes to @ftiff. Who knows how long it would have taken for me to discover that issue?

I'm surprised that contrary to Reitz's philosophy with requests (easy to use, does the heavy lifting for you) it throws an exception rather than at least _trying_ to cast a non-basestring to str. I'm sure they have good reasons for it, but I can visualize the typecasting code I would put in to just avoid it. Of course, then people ignore the proper interface rather than learn their tooling better.

I feel like there have been a lot of mysterious issues with JSSImporter that may actually resolve due to this-slack questions where first vs. subsequent runs succeed or fail for unknown reasons. Time will tell.

Either way, I need a day to go through all of the issues and PRs on JSSImporter and do a new release that bundles the new python-jss so we can close the door on this entirely.
