### ISSUE TITLE
Error mounting URL smb

### ISSUE THREAD

**Issue by ddcdennisb** [sheagcraig/JSSImporter#90]
Last week my Windows Server (main JSS DP) was patched and I ran AutoPKGr and the importer kept failing to connect to my SMB Share to upload packages.  Come to find out KB316949 was installed and this seems to break the ability to connect to an SMB share from Mac/Linux/Unix.  

I did some testing, and found that when the importer tried to connect to an SMB share, it uses the url: "smb://domain;username:password@servername:139/Sharename".  Doing some testing I found that if you removed the port number :139 the connection works fine.  (i.e. "smb://domain;username:password@servername/Sharename")

I have since removed KB3161949 but this will keep coming back as my companies server team will continue to patch the machine.

**Comment by sheagcraig** [comment]
Hi @ddcdennisb 

So first of all, very sorry to take almost a year (6 days shy!). I don't actually use JAMF products at work any longer, so I have had to focus on what I do use.

But I'm getting caught up here.

JSSImporter has predictable behavior about SMB ports.

If you are using so-called "auto" distribution point configuration (where you just specify the DP name and password), JSSImporter will use whatever is configured on your JSS in its DP config page. If this is not explicitly configured, I assume the JSS gives it the default that it thinks you should use. (I can't remember).

If you are explicitly defining all of the connection attributes for your DPs, you can just say which port you want it to use. JSSImporter uses a default port of 445, but since you're seeing 139, I'm guessing you're not in this situation.
